apiVersion: v1
kind: ServiceAccount
metadata:
  name: harporias-sa
  namespace: test
  labels:
    app.kubernetes.io/name: test

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: harporias-cr
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["watch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: harporias-crb
subjects:
- kind: ServiceAccount
  name: harporias-sa
  namespace: test
roleRef:
  kind: ClusterRole
  name: harporias-cr
  apiGroup: rbac.authorization.k8s.io